### ISSUE TITLE
invitation notifications on profile page

### ISSUE THREAD

**Issue by J-Son89** [emenlu/website#73] opened 2017-01-23 13:07 UTC
the invitations tab on the profile page should have some eye candy when you receive invitations

**Comment by smeetz** [comment] 2017-02-21 16:06
I think it's ok to just have some :sparkles: if there _exists_ any pending invites. I don't think it's worth it to create a "new notifications" type of behavior

**Comment by smeetz** [comment] 2017-03-06 15:22
Duplicate of #78

**Closed by smeetz** 2017-03-06 15:22 UTC
